"""
src/aisg/devtools/system_card.py
--------------------------------
`aisg init` -- write an ai-system-card.yaml describing the system under
assessment.

The card records what the operator asserts about their system. It is an input
to a compliance conversation, not an output of one: nothing here determines
whether a system is high-risk, and the generated file says so inline.

    aisg init                 # interactive
    aisg init --defaults      # non-interactive, for CI
"""

from __future__ import annotations

import argparse
import sys
import uuid
from pathlib import Path

__all__ = ["main", "build_parser", "render_card", "DEFAULT_CARD"]

OUTPUT_NAME = "ai-system-card.yaml"

ROLES = ("provider", "deployer", "importer", "distributor")
RISK_TIERS = ("prohibited", "high", "limited", "minimal")
DEPLOYMENTS = ("eu", "non_eu", "unknown")

# Annex III of Regulation (EU) 2024/1689 -- the high-risk use-case areas.
ANNEX_III = (
    "biometrics",
    "critical_infrastructure",
    "education_and_vocational_training",
    "employment_and_worker_management",
    "essential_services_and_benefits",
    "law_enforcement",
    "migration_asylum_and_border_control",
    "justice_and_democratic_processes",
)

DEFAULT_CARD = {
    "system": {
        "id": "",  # filled with a uuid4 at render time
        "name": "unnamed-system",
        "purpose": "TODO: describe what this system does, in one sentence.",
    },
    "role": "provider",
    "risk_tier": "unknown",
    "annex_iii_category": None,
    "affected_persons": "TODO: who is affected by this system's outputs?",
    "deployment": "unknown",
}


def _prompt(label: str, default: str, choices: tuple[str, ...] | None = None) -> str:
    """Ask once, accept the default on empty input, re-ask on an invalid choice."""
    suffix = f" [{'/'.join(choices)}]" if choices else ""
    while True:
        try:
            raw = input(f"{label}{suffix}\n  (default: {default}) > ").strip()
        except EOFError:
            # Piped stdin that ran out -- take the default rather than crash.
            print()
            return default
        value = raw or default
        if choices and value not in choices:
            print(f"  ! '{value}' is not one of: {', '.join(choices)}")
            continue
        return value


def _yaml_scalar(value: str) -> str:
    """Quote a scalar when YAML would otherwise misread it."""
    if value == "":
        return '""'
    needs_quote = (
        any(ch in value for ch in ":#{}[]&*!|>%@`\"'\n")
        or value[0].isspace()
        or value[-1].isspace()
        or value.lower() in {"true", "false", "null", "yes", "no", "on", "off", "~"}
    )
    if needs_quote:
        return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'
    return value


def render_card(card: dict) -> str:
    """Render the card as YAML by hand, so the inline caveats survive."""
    sysd = card["system"]
    lines = [
        "# ai-system-card.yaml",
        "# Generated by `aisg init`. Edit freely -- this file records what YOU",
        "# assert about the system; the tool does not verify any of it.",
        "",
        "schema: aisg/1",
        "",
        "system:",
        f"  id: {_yaml_scalar(sysd['id'])}",
        f"  name: {_yaml_scalar(sysd['name'])}",
        f"  purpose: {_yaml_scalar(sysd['purpose'])}",
        "",
        "# The party you act as for this system, per Art. 3 definitions.",
        f"role: {_yaml_scalar(card['role'])}",
        "",
        "# Risk classification is a LEGAL DETERMINATION, not a tool output.",
        "# aisg cannot decide this for you and does not try. It must be made by",
        "# someone competent to read Art. 6 and Annex III against your actual",
        "# use case, and recorded here for traceability.",
        f"risk_tier: {_yaml_scalar(card['risk_tier'])}",
        "",
    ]

    if card.get("annex_iii_category"):
        lines += [
            "# Annex III area, required when risk_tier is `high`.",
            f"annex_iii_category: {_yaml_scalar(card['annex_iii_category'])}",
        ]
    else:
        lines += [
            "# Annex III area. Required when risk_tier is `high`; null otherwise.",
            "# One of: " + ", ".join(ANNEX_III),
            "annex_iii_category: null",
        ]

    lines += [
        "",
        "# Who is affected by this system's outputs.",
        f"affected_persons: {_yaml_scalar(card['affected_persons'])}",
        "",
        "# Where the system is placed on the market or put into service.",
        f"deployment: {_yaml_scalar(card['deployment'])}",
        "",
    ]
    return "\n".join(lines)


def collect_interactive() -> dict:
    card = {k: (dict(v) if isinstance(v, dict) else v) for k, v in DEFAULT_CARD.items()}
    print("aisg init -- describe the system under assessment.")
    print("Press Enter to accept each default.\n")

    card["system"]["name"] = _prompt("System name", "unnamed-system")
    card["system"]["id"] = _prompt("System id", str(uuid.uuid4()))
    card["system"]["purpose"] = _prompt("Purpose (one sentence)", DEFAULT_CARD["system"]["purpose"])
    card["role"] = _prompt("Your role", "provider", ROLES)

    print("\n  Note: risk tier is a legal determination. aisg records your answer;")
    print("  it does not and cannot classify the system for you.")
    card["risk_tier"] = _prompt("Risk tier", "unknown", RISK_TIERS + ("unknown",))

    if card["risk_tier"] == "high":
        card["annex_iii_category"] = _prompt("Annex III category", ANNEX_III[0], ANNEX_III)
    else:
        card["annex_iii_category"] = None

    card["affected_persons"] = _prompt("Affected persons", DEFAULT_CARD["affected_persons"])
    card["deployment"] = _prompt("Deployment", "unknown", DEPLOYMENTS)
    return card


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="aisg init",
        description="Write an ai-system-card.yaml describing the system under assessment.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "The card records assertions, not findings. Risk classification is a\n"
            "legal determination that this tool does not make.\n"
        ),
    )
    p.add_argument(
        "--defaults",
        action="store_true",
        help="Skip all prompts and write a placeholder card (for CI)",
    )
    p.add_argument(
        "--output",
        "-o",
        default=OUTPUT_NAME,
        help=f"Where to write the card (default: ./{OUTPUT_NAME})",
    )
    p.add_argument(
        "--force",
        "-f",
        action="store_true",
        help="Overwrite an existing card",
    )
    return p


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    dest = Path(args.output)

    if dest.exists() and not args.force:
        print(
            f"Error: {dest} already exists. Re-run with --force to overwrite it.",
            file=sys.stderr,
        )
        return 2

    if args.defaults:
        card = {k: (dict(v) if isinstance(v, dict) else v) for k, v in DEFAULT_CARD.items()}
        card["system"]["id"] = str(uuid.uuid4())
    else:
        if not sys.stdin.isatty():
            print(
                "Error: `aisg init` is interactive and stdin is not a terminal.\n"
                "Use `aisg init --defaults` for non-interactive environments.",
                file=sys.stderr,
            )
            return 2
        try:
            card = collect_interactive()
        except KeyboardInterrupt:
            print("\nAborted; nothing written.", file=sys.stderr)
            return 130

    try:
        dest.write_text(render_card(card), encoding="utf-8")
    except OSError as exc:
        print(f"Error: could not write {dest}: {exc}", file=sys.stderr)
        return 2

    print(f"Wrote {dest}")
    if args.defaults:
        print("Placeholder values written. Fill in purpose, affected_persons and risk_tier.")
    print("risk_tier is a legal determination -- aisg recorded your answer, it did not classify.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
